name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: npm install
        run: npm i

      - name: Run Cypress tests e2e
        run: npm run cypress:headless
